name: Build Thesis
on:
    push:
    # paths-ignore:
    #   - 'CHANGELOG.md'
    pull_request:
    schedule:
        - cron: "0 11 * * *"


jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            thesis.tex


      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: thesis.pdf
